### ISSUE TITLE
Make sreamlit UI

### ISSUE THREAD

**Issue by ArtamonovDen** [drinkertea/Formula2LaTeX#10]
It should b able to:
* get latex image via drag-n-drope or paste from copy-buffer
* mock calling model inference
* return latex-formula as text

**Comment by juggeroid** [comment]
The commit related to Streamlit UI can be viewed here: https://github.com/drinkertea/Formula2LaTeX/commit/c91a81af2f716e4835273ad4d6aedd0bf32cb355 (see app.py)

It has been implemented independently and then merged without tracking the changes via GIT. The disadvantage of this approach -- the interface is not forwarded to the outside, thus no API is publicly available. 

It is impossible to move forward because of world events known to all, so the workaround is to use public Minecraft server deployed for free using remote virtual machine: (e.g. http://mc.englite.me:8501/).
